---
- hosts: all
  vars:
    downloads_dir: /tmp/downloads
  tasks:
  - name: use whole partition
    become: true
    become_method: sudo
    command: resize2fs /dev/sda1

  - name: add apt repositories
    become: true
    become_method: sudo
    apt_repository: repo={{ item }}
    with_items:
    - ppa:git-core/ppa
    - ppa:neovim-ppa/stable
    - deb [trusted=true] https://repo.iovisor.org/apt/xenial xenial-nightly main

  - name: install apt packages
    become: true
    become_method: sudo
    apt: name={{ item }} state=latest update_cache=true
    with_items:
    - automake
    - autotools-dev
    - build-essential
    - curl
    - debootstrap
    - direnv
    - exuberant-ctags
    - git
    - htop
    - libcap-dev
    - libncurses5-dev
    - libseccomp-dev
    - libtool
    - neovim
    - pkg-config
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - shellcheck
    - silversearcher-ag
    - tmux
    - tree
    - util-linux
    - valgrind
    - vim-nox
    - wget
    - zsh

  - name: install neovim pip package
    pip: name=neovim executable=/usr/bin/pip

  - name: install neovim pip3 package
    pip: name=neovim executable=/usr/bin/pip3

  - name: clone oh my zsh
    git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

  - name: set zsh as default shell
    become: true
    become_method: sudo
    user: name={{ansible_env.USER}} shell=/bin/zsh

  - name: ensure downloads directory exists
    file: path={{downloads_dir}} state=directory

  - name: copy config files
    copy: src={{item.src}} dest={{item.dst}} mode=0664 force=true
    with_items:
    - {src: config/tmux.conf, dst: ~/.tmux.conf}
    - {src: config/zshrc, dst: ~/.zshrc}
    - {src: config/gitconfig, dst: ~/.gitconfig}
    - {src: config/vimrc.local.plugins, dst: ~/.vimrc.local.plugins}

  - name: get TPM
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm

  - name: download go
    get_url: url=https://storage.googleapis.com/golang/go1.11.2.linux-amd64.tar.gz dest={{downloads_dir}}/go.tar.gz

  - name: extract go
    become: true
    become_method: sudo
    unarchive: copy=no src={{downloads_dir}}/go.tar.gz dest=/usr/local creates=/usr/local/go

  - name: clone vim config
    git: repo=https://github.com/luan/vimfiles dest=~/.vim
